
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret db_url
  commit_interval: 5
  purge_keep_days: 5
  exclude:
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Update Dynamic DNS
namecheapdns:
  domain: nstod.com
  host: "*"
  password: !secret namecheap_password

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: eero_tracker
    interval_seconds: 15

# Leviton lights
light:
  - platform: decora_wifi
    username: !secret leviton_username
    password: !secret leviton_password

tplink:
    discovery: true

rachio:
  api_key: !secret rachio_api_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: processor_use
      - type: processor_temperature
      - type: disk_use_percent
  - platform: template
    sensors:
      home_assistant_plug_current:
        friendly_name_template: "{{ states.switch.home_assistant.name}} Current"
        value_template: '{{ states.switch.home_assistant.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      home_assistant_plug_state:
        friendly_name_template: "{{ states.switch.home_assistant.name}} State"
        value_template: '{% if states.switch.home_assistant.attributes["current_power_w"] | float > 1.5 %} Running {% else %} Idle {% endif %}'
      home_assistant_plug_power:
        friendly_name_template: "{{ states.switch.home_assistant.name}} Current Consumption"
        value_template: '{{ states.switch.home_assistant.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      home_assistant_plug_total_consumption:
        friendly_name_template: "{{ states.switch.home_assistant.name}} Total Consumption"
        value_template: '{{ states.switch.home_assistant.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      home_assistant_plug_voltage:
        friendly_name_template: "{{ states.switch.home_assistant.name}} Voltage"
        value_template: '{{ states.switch.home_assistant.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      home_assistant_plug_today_consumption:
        friendly_name_template: "{{ states.switch.home_assistant.name}} Today's Consumption"
        value_template: '{{ states.switch.home_assistant.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washing_machine_current:
        friendly_name_template: "{{ states.switch.washer.name}} Current"
        value_template: '{{ states.switch.washer.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washing_machine_state:
        friendly_name_template: "{{ states.switch.washer.name}} State"
        value_template: '{% if states.switch.washer.attributes["current_power_w"] | float > 1.5 %} Running {% else %} Idle {% endif %}'
      washing_machine_power:
        friendly_name_template: "{{ states.switch.washer.name}} Current Consumption"
        value_template: '{{ states.switch.washer.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washing_machine_total_consumption:
        friendly_name_template: "{{ states.switch.washer.name}} Total Consumption"
        value_template: '{{ states.switch.washer.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washing_machine_voltage:
        friendly_name_template: "{{ states.switch.washer.name}} Voltage"
        value_template: '{{ states.switch.washer.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      washing_machine_today_consumption:
        friendly_name_template: "{{ states.switch.washer.name}} Today's Consumption"
        value_template: '{{ states.switch.washer.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      front_yard_sprinkler:
        friendly_name_template: "{{ states.switch.front_yard.name }}"
        value_template: '{% if is_state("switch.front_yard", "on") %} 1 {% else %} 0 {% endif %}'
        unit_of_measurement: 'state'
      back_door_sprinkler:
        friendly_name_template: "{{ states.switch.back_door.name }}"
        value_template: '{% if is_state("switch.back_door", "on") %} 1 {% else %} 0 {% endif %}'
        unit_of_measurement: 'state'
      back_fence_sprinkler:
        friendly_name_template: "{{ states.switch.back_fence.name }}"
        value_template: '{% if is_state("switch.back_fence", "on") %} 1 {% else %} 0 {% endif %}'
        unit_of_measurement: 'state'
      drip_sprinkler:
        friendly_name_template: "{{ states.switch.drip.name }}"
        value_template: '{% if is_state("switch.drip", "on") %} 1 {% else %} 0 {% endif %}'
        unit_of_measurement: 'state'
      living_room_current_temperature:
        friendly_name_template: "{{ states.climate.living_room.name}} Current Temp"
        value_template: '{{states.climate.living_room.attributes["current_temperature"] | float | round(0)}}'
        unit_of_measurement: '°F'
  - platform: aquahawk
    resource: https://sterco.aquahawk.us
    value_template: '{{ value_json.meters[0].metricAggregates.waterUseActual.current["1 hour"].gallons }}'
    unit_of_measurement: gallons
    username: !secret aquahawk_username
    password: !secret aquahawk_password
    name: Water Meter
    headers:
      accept: application/json
      Content-Type: application/x-www-form-urlencoded
  - platform: aquahawk
    resource: https://sterco.aquahawk.us
    value_template: '{{ value_json.meters[0].metricAggregates.waterUseActual.current["billing period"].gallons }}'
    unit_of_measurement: gallons
    username: !secret aquahawk_username
    password: !secret aquahawk_password
    name: Water Meter Current Month
    headers:
      accept: application/json
      Content-Type: application/x-www-form-urlencoded
  - platform: aquahawk
    resource: https://sterco.aquahawk.us
    value_template: '{{ value_json.meters[0].metricAggregates.waterUse.projected["billing period"].gallons }}'
    unit_of_measurement: gallons
    username: !secret aquahawk_username
    password: !secret aquahawk_password
    name: Water Meter Projected
    headers:
      accept: application/json
      Content-Type: application/x-www-form-urlencoded